In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movie.csv").set_index('director_name').sort_index()

In [3]:
df.head(10)

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Aaron Hann,Color,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,Jordi Vilasuso,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Aaron Schneider,Color,160.0,100.0,11.0,970.0,Robert Duvall,13000.0,9176553.0,Drama|Mystery,Bill Murray,...,97.0,English,USA,PG-13,7500000.0,2009.0,3000.0,7.1,2.35,0
Aaron Seltzer,Color,99.0,85.0,64.0,729.0,Carmen Electra,3000.0,48546578.0,Comedy|Romance,Alyson Hannigan,...,613.0,English,USA,PG-13,20000000.0,2006.0,869.0,2.7,1.85,806
Abel Ferrara,Color,48.0,99.0,220.0,599.0,Vincent Gallo,812.0,1227324.0,Crime|Drama,Isabella Rossellini,...,48.0,English,USA,R,12500000.0,1996.0,787.0,6.6,1.85,344
Adam Brooks,Color,160.0,112.0,20.0,61.0,Sakina Jaffrey,16000.0,31973840.0,Comedy|Drama|Romance,Ryan Reynolds,...,168.0,English,Germany,PG-13,NaN,2008.0,109.0,7.2,2.35,0
Adam Carolla,Color,14.0,98.0,102.0,360.0,Jim O'Heir,563.0,105943.0,Comedy,Jay Mohr,...,11.0,English,USA,NaN,1500000.0,2015.0,485.0,6.1,NaN,212
Adam Goldberg,Color,22.0,111.0,1000.0,127.0,Marisa Coughlan,2000.0,2580.0,Drama|Mystery,Judy Greer,...,40.0,English,USA,R,1650000.0,2003.0,163.0,5.4,2.35,63
Adam Green,Color,229.0,93.0,134.0,488.0,Kane Hodder,936.0,NaN,Comedy|Horror,Joel David Moore,...,235.0,English,USA,R,1500000.0,2006.0,935.0,5.7,1.85,0
Adam Jay Epstein,Color,14.0,76.0,0.0,227.0,Denise Boutte,387.0,NaN,Comedy,Rich Ceraulo,...,35.0,English,USA,R,NaN,2008.0,295.0,3.8,1.85,636

`Head` and `Tail`
------------------

In [4]:
df.head(1) #first row

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128

In [ ]:
df.tail(4)  #last 4 rows

`Access Columns`
-----------------

In [ ]:
#using lists for column names

In [6]:
df['num_critic_for_reviews'].head(10)

director_name
A. Raven Cruz         3.0
Aaron Hann           29.0
Aaron Schneider     160.0
Aaron Seltzer        99.0
Abel Ferrara         48.0
Adam Brooks         160.0
Adam Carolla         14.0
Adam Goldberg        22.0
Adam Green          229.0
Adam Jay Epstein     14.0
Name: num_critic_for_reviews, dtype: float64

In [7]:
df.num_critic_for_reviews.head(10) # attribute method

director_name
A. Raven Cruz         3.0
Aaron Hann           29.0
Aaron Schneider     160.0
Aaron Seltzer        99.0
Abel Ferrara         48.0
Adam Brooks         160.0
Adam Carolla         14.0
Adam Goldberg        22.0
Adam Green          229.0
Adam Jay Epstein     14.0
Name: num_critic_for_reviews, dtype: float64

In [8]:
df[['num_critic_for_reviews', 'actor_3_facebook_likes']].head(10) #multiple columns

                  num_critic_for_reviews  actor_3_facebook_likes
director_name
A. Raven Cruz                        3.0                    94.0
Aaron Hann                          29.0                    94.0
Aaron Schneider                    160.0                   970.0
Aaron Seltzer                       99.0                   729.0
Abel Ferrara                        48.0                   599.0
Adam Brooks                        160.0                    61.0
Adam Carolla                        14.0                   360.0
Adam Goldberg                       22.0                   127.0
Adam Green                         229.0                   488.0
Adam Jay Epstein                    14.0                   227.0

In [9]:
df[['num_critic_for_reviews', 'duration']].head(10) #multiple columns

                  num_critic_for_reviews  duration
director_name
A. Raven Cruz                        3.0      97.0
Aaron Hann                          29.0      87.0
Aaron Schneider                    160.0     100.0
Aaron Seltzer                       99.0      85.0
Abel Ferrara                        48.0      99.0
Adam Brooks                        160.0     112.0
Adam Carolla                        14.0      98.0
Adam Goldberg                       22.0     111.0
Adam Green                         229.0      93.0
Adam Jay Epstein                    14.0      76.0

`Row Selection / Slicing`
--------------------------

In [10]:
#For rows, list slicing

df[:3] #only rows, for convenice purposes

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Aaron Hann,Color,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,Jordi Vilasuso,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Aaron Schneider,Color,160.0,100.0,11.0,970.0,Robert Duvall,13000.0,9176553.0,Drama|Mystery,Bill Murray,...,97.0,English,USA,PG-13,7500000.0,2009.0,3000.0,7.1,2.35,0

In [11]:
df[:3]['duration']  #row then column

director_name
A. Raven Cruz       97.0
Aaron Hann          87.0
Aaron Schneider    100.0
Name: duration, dtype: float64

In [12]:
df[:3][['duration', 'actor_2_name']] #row then multiple columns

                 duration        actor_2_name
director_name
A. Raven Cruz        97.0         Vanilla Ice
Aaron Hann           87.0  Michael McLafferty
Aaron Schneider     100.0       Robert Duvall

`loc`  
------
 (label based)

In [13]:
df.loc['A. Raven Cruz': 'Adam Brooks'] #not numbers

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Aaron Hann,Color,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,Jordi Vilasuso,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Aaron Schneider,Color,160.0,100.0,11.0,970.0,Robert Duvall,13000.0,9176553.0,Drama|Mystery,Bill Murray,...,97.0,English,USA,PG-13,7500000.0,2009.0,3000.0,7.1,2.35,0
Aaron Seltzer,Color,99.0,85.0,64.0,729.0,Carmen Electra,3000.0,48546578.0,Comedy|Romance,Alyson Hannigan,...,613.0,English,USA,PG-13,20000000.0,2006.0,869.0,2.7,1.85,806
Abel Ferrara,Color,48.0,99.0,220.0,599.0,Vincent Gallo,812.0,1227324.0,Crime|Drama,Isabella Rossellini,...,48.0,English,USA,R,12500000.0,1996.0,787.0,6.6,1.85,344
Adam Brooks,Color,160.0,112.0,20.0,61.0,Sakina Jaffrey,16000.0,31973840.0,Comedy|Drama|Romance,Ryan Reynolds,...,168.0,English,Germany,PG-13,NaN,2008.0,109.0,7.2,2.35,0

In [ ]:
#Index on columns as well

In [14]:
df.loc['A. Raven Cruz': 'Adam Brooks', 'num_critic_for_reviews']

director_name
A. Raven Cruz        3.0
Aaron Hann          29.0
Aaron Schneider    160.0
Aaron Seltzer       99.0
Abel Ferrara        48.0
Adam Brooks        160.0
Name: num_critic_for_reviews, dtype: float64

In [15]:
df.loc['A. Raven Cruz': 'Adam Brooks',['num_critic_for_reviews', 'color']]

                 num_critic_for_reviews  color
director_name
A. Raven Cruz                       3.0  Color
Aaron Hann                         29.0  Color
Aaron Schneider                   160.0  Color
Aaron Seltzer                      99.0  Color
Abel Ferrara                       48.0  Color
Adam Brooks                       160.0  Color

`iloc`
-------

integer-based

In [16]:
df.iloc[0:6] #first six rows

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Aaron Hann,Color,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,Jordi Vilasuso,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Aaron Schneider,Color,160.0,100.0,11.0,970.0,Robert Duvall,13000.0,9176553.0,Drama|Mystery,Bill Murray,...,97.0,English,USA,PG-13,7500000.0,2009.0,3000.0,7.1,2.35,0
Aaron Seltzer,Color,99.0,85.0,64.0,729.0,Carmen Electra,3000.0,48546578.0,Comedy|Romance,Alyson Hannigan,...,613.0,English,USA,PG-13,20000000.0,2006.0,869.0,2.7,1.85,806
Abel Ferrara,Color,48.0,99.0,220.0,599.0,Vincent Gallo,812.0,1227324.0,Crime|Drama,Isabella Rossellini,...,48.0,English,USA,R,12500000.0,1996.0,787.0,6.6,1.85,344
Adam Brooks,Color,160.0,112.0,20.0,61.0,Sakina Jaffrey,16000.0,31973840.0,Comedy|Drama|Romance,Ryan Reynolds,...,168.0,English,Germany,PG-13,NaN,2008.0,109.0,7.2,2.35,0

In [17]:
df.iloc[0:6, 1:3] #columns also integer based

                 num_critic_for_reviews  duration
director_name
A. Raven Cruz                       3.0      97.0
Aaron Hann                         29.0      87.0
Aaron Schneider                   160.0     100.0
Aaron Seltzer                      99.0      85.0
Abel Ferrara                       48.0      99.0
Adam Brooks                       160.0     112.0

In [18]:
df.iloc[[1, 3, 5], [1, 3]] #scatter indices

               num_critic_for_reviews  director_facebook_likes
director_name
Aaron Hann                       29.0                      0.0
Aaron Seltzer                    99.0                     64.0
Adam Brooks                     160.0                     20.0

`Boolean indexing`
---------------------

In [20]:
df.loc[df.num_critic_for_reviews > 100, 'num_critic_for_reviews'].head()

director_name
Aaron Schneider    160.0
Adam Brooks        160.0
Adam Green         229.0
Adam Marcus        112.0
Adam McKay         265.0
Name: num_critic_for_reviews, dtype: float64

In [ ]:
#& (and)  | (or), ~not

In [22]:
df.loc[(df.num_critic_for_reviews > 100) & (df.director_facebook_likes> 200)].head()  #use brackets!

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
Adam McKay,Color,265.0,116.0,285.0,107.0,Will Ferrell,12000.0,119219978.0,Action|Comedy|Crime,Dwayne Johnson,...,316.0,English,USA,PG-13,100000000.0,2010.0,8000.0,6.7,2.35,16000
Adam McKay,Color,181.0,98.0,285.0,7000.0,Will Ferrell,640000.0,84136909.0,Comedy,Darcy Donavan,...,577.0,English,USA,PG-13,26000000.0,2004.0,8000.0,7.2,1.85,0
Adam McKay,Color,173.0,106.0,285.0,105.0,Adam Scott,8000.0,100468793.0,Comedy,Will Ferrell,...,277.0,English,USA,R,65000000.0,2008.0,3000.0,6.9,2.35,0
Adam McKay,Color,164.0,122.0,285.0,989.0,Leslie Bibb,8000.0,148213377.0,Action|Comedy|Sport,Will Ferrell,...,437.0,English,USA,PG-13,73000000.0,2006.0,1000.0,6.6,2.35,0
Adam McKay,Color,272.0,143.0,285.0,7000.0,Will Ferrell,11000.0,2175312.0,Comedy,Harrison Ford,...,346.0,English,USA,PG-13,50000000.0,2013.0,8000.0,6.3,2.35,41000

In [23]:
df.loc[(df.num_critic_for_reviews == 100.0)].head() #exact match

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
Barry Levinson,Color,100.0,133.0,272.0,628.0,Valeria Golino,10000.0,172825435.0,Drama,Tom Cruise,...,331.0,English,USA,R,25000000.0,1988.0,898.0,8.0,1.85,12000
Bart Freundlich,Color,100.0,103.0,38.0,316.0,Garry Shandling,745.0,1530535.0,Comedy|Drama|Romance,Billy Crudup,...,63.0,English,USA,R,9000000.0,2005.0,591.0,5.7,2.35,215
Bruce Campbell,Color,100.0,84.0,0.0,158.0,Dan Hicks,634.0,173066.0,Comedy|Fantasy,Ted Raimi,...,88.0,English,USA,R,1500000.0,2007.0,328.0,6.3,1.85,0
Chuck Russell,Color,100.0,107.0,55.0,294.0,Jimmy Smits,3000.0,29374178.0,Crime|Drama|Horror|Thriller,Rufus Sewell,...,188.0,English,USA,R,40000000.0,2000.0,941.0,5.1,2.35,394
George Lucas,Color,100.0,112.0,0.0,425.0,Ron Howard,11000.0,115000000.0,Comedy|Drama|Music,Harrison Ford,...,238.0,English,USA,PG,777000.0,1973.0,2000.0,7.5,2.35,0

In [24]:
df.loc[~(df.num_critic_for_reviews > 100) & ~(df.director_facebook_likes> 100)].head()

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Aaron Hann,Color,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,Jordi Vilasuso,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Aaron Seltzer,Color,99.0,85.0,64.0,729.0,Carmen Electra,3000.0,48546578.0,Comedy|Romance,Alyson Hannigan,...,613.0,English,USA,PG-13,20000000.0,2006.0,869.0,2.7,1.85,806
Adam Jay Epstein,Color,14.0,76.0,0.0,227.0,Denise Boutte,387.0,NaN,Comedy,Rich Ceraulo,...,35.0,English,USA,R,NaN,2008.0,295.0,3.8,1.85,636
Adam Rapp,Color,50.0,98.0,9.0,405.0,Will Ferrell,11000.0,101228.0,Comedy|Drama,Zooey Deschanel,...,53.0,English,USA,R,3500000.0,2005.0,8000.0,6.4,1.85,414

In [25]:
df.loc[(df.actor_2_name.str.startswith("V")) & ~(df.director_facebook_likes> 100)].head()

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Color,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,Scott Levy,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Andy Garcia,Color,52.0,144.0,0.0,195.0,Victor Rivers,786.0,2483955.0,Drama|Romance,Danny Pino,...,165.0,English,USA,R,9600000.0,2005.0,228.0,6.7,1.85,957
Antony Hoffman,Color,145.0,106.0,14.0,0.0,Val Kilmer,2.0,17473245.0,Action|Sci-Fi|Thriller,Bob Neill,...,348.0,English,USA,PG-13,70000000.0,2000.0,0.0,5.7,2.35,995
Barry W. Blaustein,Color,70.0,108.0,6.0,43.0,Vince McMahon,54.0,2047570.0,Biography|Documentary|Sport,Terry Funk,...,80.0,English,USA,R,500000.0,1999.0,44.0,7.6,1.85,491
Betty Thomas,Color,116.0,103.0,84.0,664.0,Viggo Mortensen,12000.0,37035515.0,Comedy|Drama,Steve Buscemi,...,194.0,English,USA,PG-13,43000000.0,2000.0,10000.0,6.0,1.37,0

`Callable`
---------------------

In [ ]:
#Grab all rows where df.num_critic_for_reviews > 0 and all columns

In [ ]:
df.loc[lambda df: df.num_critic_for_reviews > 100, :]

In [27]:
df.loc[: ,lambda df: ['num_critic_for_reviews']].head()

                 num_critic_for_reviews
director_name
A. Raven Cruz                       3.0
Aaron Hann                         29.0
Aaron Schneider                   160.0
Aaron Seltzer                      99.0
Abel Ferrara                       48.0